logging:
  level:
    root: INFO
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: INFO
    cn.com.taiji.security.securityday1: debug

spring:
  datasource:
    url: jdbc:mysql://192.168.70.40:3306/securityclass?serverTimezone=GMT%2B8&amp&useSSL=false&characterEncoding=utf-8
    username: tdfcloud
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop